#!/usr/bin/env node
import * as yargs from "yargs";
import { Loz } from "./index";

const LOZ_DEBUG = process.env.DEBUG === "true" ? true : false;

const args = yargs
  .wrap(null)
  .command("$0 [prompt]", "Loz: a simple CLI for LLM", (yargs) => {
    yargs.positional("prompt", {
      description: "Prompt to answer",
      type: "string",
    });
  })
  .options({
    interactive: {
      alias: "i",
      describe: "Interactive mode",
    },
    git: {
      alias: "g",
      describe:
        "Generate a Git commit message that summarizes the changes made in the diff",
    },
    commit: {
      alias: "c",
      describe: "Generate a Git commit message in the current git repository",
    },
    log: {
      alias: "l",
      describe:
        // generated by copilot
        "Log the conversation to a file. The file name is the current date and time",
    },
  })
  .help()
  .parseSync();

const loz = new Loz();

async function handleLozCommand() {
  if (args.prompt) {
    await handlePrompt(args.prompt);
  } else if (args.git) {
    await handleGitCommand();
  } else {
    await handleDefaultCase();
  }
}

async function handlePrompt(prompt: any) {
  if (prompt === "commit") {
    await loz.runGitCommit();
    loz.saveChatHistory();
  } else {
    await handlePromptInput(prompt);
  }
}

async function handlePromptInput(prompt: any) {
  if (!process.stdin.isTTY) {
    await loz.handlePipeInput(prompt);
  } else {
    const completion = await loz.completeUserPrompt(prompt);
    console.log(completion.content);
  }
}

async function handleGitCommand() {
  if (!process.stdin.isTTY) {
    await loz.writeGitCommitMessage();
  } else {
    console.log("Run loz like this: git diff | loz --git");
  }
}

async function handleDefaultCase() {
  if (!process.stdin.isTTY) {
    console.log("Input your prompt:");
    process.exit(0);
  }
  console.log("Loz: a simple CLI for LLM");
  try {
    while (true) {
      const res = await loz.runPromptInteractiveMode();
      if (res === "Done") break;
    }
  } catch (error) {
    console.log(error);
  }
  console.log("Good bye!");
  loz.saveChatHistory();
  process.exit(0);
}

(async () => {
  await loz.init();
  await handleLozCommand();
})();
